
name = "payly-lat"
compatibility_date = "2024-03-06"
main = "dist/index.js"
nodejs_compat = true

[site]
bucket = "./dist/public"

[build]
command = "npm run build"

# Add this section to properly handle static assets
[assets]
dir = "dist/public"
