
name = "payly"
compatibility_date = "2024-03-06"
main = "dist/index.js"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./dist/public"

[build]
command = "npm run build"

[triggers]
crons = []

[dev]
port = 8787
