
name = "payly"
compatibility_date = "2024-03-06"
main = "dist/index.js"
node_compat = true

[site]
bucket = "./dist/public"

[build]
command = "npm run build"

# Static assets configuration
[[rules]]
type = "CommonJS"
globs = ["**/*.js"]

# Route all requests to our SPA
[[routes]]
pattern = "/*"
custom_domain = true
script = "dist/index.js"

# Ensure all asset requests are properly handled
[[rules]]
type = "ESModule"
globs = ["dist/index.js"]

[dev]
port = 8787
