
name = "payly"
compatibility_date = "2024-03-06"
main = "dist/index.js"
node_compat = true

[site]
bucket = "./dist/public"

[build]
command = "npm run build"

# Configure Cloudflare Pages-like static asset serving
[site.static]
root = "dist/public"
include = ["**/*"]
fallback_document = "index.html"

# Define routes for the worker
[[routes]]
pattern = "/api/*"
script = "dist/index.js"

[[routes]]
pattern = "/*"
script = "dist/index.js"

[dev]
port = 8787
